name: MLOps Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install flake8
      - run: flake8 .

  build-test-train:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python tests/test_model_pipeline.py
      - name: Train model
        run: python src/model_training.py
      - name: Upload run_id artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-id
          path: run_id.txt
      - name: Upload models
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/
      - name: Upload mlruns artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/
      - name: Evaluate model
        run: python src/model_evaluation.py

  model-register:
    runs-on: ubuntu-latest
    needs: build-test-train
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Download run_id artifact
        uses: actions/download-artifact@v4
        with:
          name: run-id
          path: .
      - name: Download mlruns artifact
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns/
      - run: pip install -r requirements.txt
      - name: Register Model in MLflow
        run: |
          RUN_ID=$(cat run_id.txt)
          export RUN_ID
          python src/model_register.py

  deploy:
    runs-on: ubuntu-latest
    needs: model-register
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Download mlruns artifact
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns/
      - run: pip install mlflow[extras]
      # Serve the last model (for real production, push image or upload to model serving infra)
      - run: |
          mlflow models serve \
          -m "mlruns/0/$(ls -td mlruns/0/*/ | head -n1 | xargs -n1 basename)/artifacts/model"\
            --no-conda -p 5000 --env-manager local &
